version: '3.9'
services:
  db:
    image: postgres:15
    container_name: fullstack-db
    restart: always
    environment:
      POSTGRES_DB: fullstack_app
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
